// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChGTxijpGME3fsGaasriKG8cA5BBYfJwA',
    appId: '1:690273865156:android:a962fa5671b5df3a936891',
    messagingSenderId: '690273865156',
    projectId: 'aya-application',
    storageBucket: 'aya-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiYSXrR5lLwXhXdkzEEUT7vMT052tAGvw',
    appId: '1:690273865156:ios:983e26a4c9fdef04936891',
    messagingSenderId: '690273865156',
    projectId: 'aya-application',
    storageBucket: 'aya-application.firebasestorage.app',
    iosClientId: '690273865156-nuic8u5rmbtf88qd9ilfhlu0p72osv0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayaMobileAppReal',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOVNA6EXb0UcjpHkJxC1VB3KyY1YeanVU',
    appId: '1:690273865156:web:901b40a2f9b6a45f936891',
    messagingSenderId: '690273865156',
    projectId: 'aya-application',
    authDomain: 'aya-application.firebaseapp.com',
    storageBucket: 'aya-application.firebasestorage.app',
    measurementId: 'G-PLQQTZ539G',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiYSXrR5lLwXhXdkzEEUT7vMT052tAGvw',
    appId: '1:690273865156:ios:983e26a4c9fdef04936891',
    messagingSenderId: '690273865156',
    projectId: 'aya-application',
    storageBucket: 'aya-application.firebasestorage.app',
    iosClientId: '690273865156-nuic8u5rmbtf88qd9ilfhlu0p72osv0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayaMobileAppReal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOVNA6EXb0UcjpHkJxC1VB3KyY1YeanVU',
    appId: '1:690273865156:web:ae7d0326c911c128936891',
    messagingSenderId: '690273865156',
    projectId: 'aya-application',
    authDomain: 'aya-application.firebaseapp.com',
    storageBucket: 'aya-application.firebasestorage.app',
    measurementId: 'G-5Z657FJNN7',
  );

}